### PR TITLE
Update config.json

### PR DESCRIPTION
**Pull request by deepanshu88**
Add Blog "https://www.listendata.com/"

### CODE REVIEW

**Comment by rgommers** [comment]
Hi @deepanshu88, do you have a Python specific feed as well? It would be good to include your Python post, but probably better not your R and other posts.

**Comment by deepanshu88** [comment]
Sure. Python specific feed URL : https://www.listendata.com/feeds/posts/default/-/Python

**Comment by rgommers** [comment]
Thanks @deepanshu88, that looks good to me. 

Note that this PR can take a while to get merged. I can't help with that, just saw this PR when adding my own.

**Comment by deepanshu88** [comment]
Thanks @rgommers. Take your time and let me know once done. Cheers!

**Pull request merged**
