### PR TITLE
Add scikit-learn blog

### PR DESCRIPTION
**Pull request by francoisgoupil**
we just created the official blog for the scikit-learn machine learning library and we want to share it to the community.
https://blog.scikit-learn.org/

### CODE REVIEW

**Comment by pv** [comment]
Actually, the url needs to be the one that server the RSS / Atom feed. So the blog entries will not appear currently, since the url points now to the HTML page, which cannot be parsed automatically.

I couldn't find the feed url on your blog (in one minute), maybe you can send another pull request correcting the url.

**Comment by pv** [comment]
Never mind, found it now. Fixed in ab7b6d837d10b

**Comment by francoisgoupil** [comment]
Thanks @pv

**Comment by pv** [comment]
Note that the feed.xml of that page probably needs corrections: e.g. href links point to scikit-learn.org, not to blog.scikit-learn.org, so the links to the full blog posts don't work.

**Pull request merged**
